### PR TITLE
Add get switch sessions

### LINKED ISSUE #157: Switch routes needed for Abstract swtich
We are migrating the LabVIEW TSM code to python for one of our customer. For one of the driver we need for the migration to be complete is the Swtich driver. 

Customer is not using all the Switch APIs in TSM. To be specific, "Get Switch sessions" is one of the primary function that they are using to get the routes from the pin map file for the Abstract switch operation.  
So please make this Function available for us to use in the application. 

Note: 
        Abstract switch uses DO from Daqmx, FPGA, DPI etc to make a connection. It helps simplify the code for the customer to run the test code on different systems with available IOs with different Pinmaps on each system.

### PR DESCRIPTION
**Pull request by smooresni**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nitsm-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds methods to query switch names and sessions.

### Why should this Pull Request be merged?

Resolves #157 

### What testing has been done?

- [x] I have run the automated tests (required if there are code changes)

### CODE REVIEW

**Comment by smooresni** [comment]
fyi @ni-erikcrank this one in work

**Review by ni-erikcrank — CHANGES_REQUESTED** [review]

**Review by ni-erikcrank — APPROVED** [review]

**Pull request merged**
